name: Isolated Functions
concurrency: Isolated Functions

on: 
  workflow_dispatch:
  push:
    paths:
      - 'articles/**'     
      - '.github/**'

jobs:  
  build:
    name: CI Validations
    uses: ./.github/workflows/ci-validation-checks.yml