
# @name = invalidOrderSchema
POST {{baseUrl}}/api/orders
Content-Type: application/json

{
  "invalid": "blah!"
}

###

# @name = createOrder
POST {{baseUrl}}/api/orders
Content-Type: application/json

{
  "orderId": "ORD_000123",
  "referenceId": "bruce.wayne@gotham.com"
}