name: Articles Validation Checks

on:
  workflow_call:
    
permissions: 
  contents: read

jobs:
  checklist:
    name: Checklist
    runs-on: ubuntu-latest
    strategy: 
        matrix:
            project-name:
            - articles/BunsenBurner/tests/ToDoApi.BunsenBurner.Tests/ToDoApi.BunsenBurner.Tests.csproj
            - articles/BunsenBurner/tests/ToDoApi.Tests/ToDoApi.Tests.csproj
            - articles/ResilientHttpClients/tests/ResilientHttpClients.Services.Tests/ResilientHttpClients.Services.Tests.csproj
            - articles/IsolatedFunctions/tests/OrderProcessorFuncApp.Tests/OrderProcessorFuncApp.Tests.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Install DotNet Tools and Run Husky
        run: |
          dotnet tool restore && \
          dotnet husky install && \
          dotnet husky run -g "lint"
        
      - name: Restore Dependencies
        run: dotnet restore ${{matrix.project-name}}

      - name: Build Project
        run: dotnet build --configuration Release --no-restore ${{matrix.project-name}}
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" ${{matrix.project-name}}