name: CI Articles
concurrency: CI Articles

on:
  push:
    paths:
      - 'articles/**'     
      - '.github/**'
  workflow_dispatch:

jobs:  
  build:
    name: CI Articles
    uses: ./.github/workflows/articles-validation-checks.yml