name: Create Release for PR
concurrency: Create Release for PR

on:
  push:
    paths:
      - 'articles/IsolatedFunctions/**'
      - '.github/**'

jobs:
  ci_validations:
    name: Build, Test and Lint
    uses: ./.github/workflows/restore-and-build.yml
    with:
      project-path: ./articles/IsolatedFunctions/src/OrderProcessorFuncApp/OrderProcessorFuncApp.csproj
      dotnet-version: '8.0.x'
  
  generate_version_number:
    name: Generate Version Number
    runs-on: ubuntu-latest
    needs:
      - ci_validations
    steps:
      - name: Build Version Number
        shell: bash
        run: |
          echo "BUILD_VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
    
    outputs:
      VersionNumber: ${{ env.BUILD_VERSION }}