name: CI Validations

on:
  workflow_call:

jobs:
  checklist:
    name: Checklist
    runs-on: ubuntu-latest
    strategy: 
        matrix:
            project-name:
            - articles/BunsenBurner/tests/ToDoApi.BunsenBurner.Tests/ToDoApi.BunsenBurner.Tests.csproj
            - articles/BunsenBurner/tests/ToDoApi.Tests/ToDoApi.Tests.csproj
            - articles/ResilientHttpClients/tests/ResilientHttpClients.Services.Tests/ResilientHttpClients.Services.Tests.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Check C# Code Formatting
        run: dotnet csharpier . --check
        
      - name: Restore Dependencies
        run: dotnet restore ${{matrix.project-name}}

      - name: Build Project
        run: dotnet build --configuration Release --no-restore ${{matrix.project-name}}
        
#      - name: Test
#        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" ${{matrix.project-name}}

      - name: Test with coverage
        run: |
          # Run tests for all projects with coverage
          dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory TestResults
          
          # Install reportgenerator if not already present
          dotnet tool install -g dotnet-reportgenerator-globaltool
          
          # Merge all coverage files and generate combined report
          reportgenerator `
            -reports:./**/coverage.cobertura.xml `
            -targetdir:./CombinedCoverageReport `
            -reporttypes:"Cobertura" `
            -sourcedirs:${{ github.workspace }}

      - name: Check combined coverage
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.10
        with:
          reports: 'CombinedCoverageReport/Cobertura.xml'
          reporttypes: 'HtmlInline'
          coverageThreshold: '80'  # Overall solution threshold