name: Create Release for PR
concurrency: Create Release for PR

on:
  push:
    paths:
      - 'articles/IsolatedFunctions/**'
      - '.github/**'

permissions: 
    contents: read

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci-isolated-functions.yml
    with:
      project-path: articles/IsolatedFunctions/tests/OrderProcessorFuncApp.Tests/OrderProcessorFuncApp.Tests.csproj
      
  generate_version_number:
    name: Generate Version Number
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: Build Version Number
        shell: bash
        run: |
          echo "BUILD_VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
    
    outputs:
      VersionNumber: ${{ env.BUILD_VERSION }}
  
  build_and_publish:
    name: Build and Publish
    needs:
      - generate_version_number
    uses: ./.github/workflows/build-and-publish-artifacts.yml
    with:
        project-path: articles/IsolatedFunctions/src/OrderProcessorFuncApp/OrderProcessorFuncApp.csproj
        versionNumber: ${{ needs.generate_version_number.outputs.VersionNumber }}      