name: Order Processor Func App Create Release for PR
concurrency: Order Processor Func App Create Release for PR

on:
  push:
    paths:
      - 'articles/IsolatedFunctions/**'
      - '.github/**'

permissions: 
    contents: read

jobs:
  ci:
    name: CI Order Processor
    uses: ./.github/workflows/ci-application.yml
    with:
      project-path: articles/IsolatedFunctions/tests/OrderProcessorFuncApp.Tests/OrderProcessorFuncApp.Tests.csproj
      
  generate_version_number:
    name: Generate Version Number
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: Build Version Number
        shell: bash
        run: |
          echo "BUILD_VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
    
    outputs:
      VersionNumber: ${{ env.BUILD_VERSION }}
  
  build_and_publish:
    name: Build and Publish
    needs:
      - generate_version_number
    uses: ./.github/workflows/build-and-publish-artifacts.yml
    with:
        project-path: articles/IsolatedFunctions/src/OrderProcessorFuncApp/OrderProcessorFuncApp.csproj
        deploy-templates-path: ./.github/bicep-order-processor-func-app
        versionNumber: ${{ needs.generate_version_number.outputs.VersionNumber }}   
          
  DEV:
    name: DEV
    needs:
      - generate_version_number
      - build_and_publish
    uses: ./.github/workflows/deploy.yml
    with:
      applicationName: funky-opf
      location: australiasoutheast
      versionNumber: ${{ needs.generate_version_number.outputs.VersionNumber }}
      environment: DEV
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}          