name: cicd_order-processor_func_app
concurrency: cicd_order-processor_func_app

on:
  workflow_dispatch:
  push:
    paths:
      - 'articles/IsolatedFunctions/**'
      - '.github/**'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci-application.yml
    with:
      project-path: articles/IsolatedFunctions/tests/OrderProcessorFuncApp.Tests/OrderProcessorFuncApp.Tests.csproj
  
  deploy_to_non_prod:
    name: Deploy to ${{ matrix.env }}
    needs:
      - ci
    strategy:
      matrix:
        env: [dev, qa]
    uses: ./.github/workflows/deploy-function-app.yml
    with:
      environment: ${{ matrix.env }}
      skip_provisioning: false
      app_name: funky-opf
      deployment_name: funky-opf-${{ matrix.env }}
      function_app_name: cchat-fn-funky-opf-${{ matrix.env }}
      project_path: articles/IsolatedFunctions/src/OrderProcessorFuncApp/OrderProcessorFuncApp.csproj
      deploy_templates_path: .github/bicep-order-processor-func-app
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
