name: cicd
concurrency: cicd

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy_to_non_prod:
    name: Deploy to ${{ matrix.env }}
    strategy:
      matrix:
        env: [dev, qa]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ matrix.env }}
      app_name: funky-opf
      deployment_name: funky-opf-${{ matrix.env }}
      function_app_name: cchat-fn-funky-opf-${{ matrix.env }}
      project_path: articles/IsolatedFunctions/src/OrderProcessorFuncApp/OrderProcessorFuncApp.csproj
      deploy_templates_path: .github/bicep-order-processor-func-app
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
