name: Provision Resources

on:
  workflow_call:
    inputs:
      applicationName:
        type: string
        required: true
        description: Application name
        
      environment:
        type: string
        required: true
        description: Environment name
      
      location:
        type: string
        required: true
        description: Resource group location
      
      versionNumber:
        type: string
        required: true
        description: Version number to track deployments
        
    secrets:
      subscriptionId:
        required: true
        description: Azure subscription id
      credentials:
        required: true
        description: Azure service principal details used to provision Azure resources
        
jobs:
  provisioning:
    name: Provisioning
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:      
      - name: Download deployment artifacts
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: deploy
          
      - name: Download Application Binaries
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.versionNumber }}
          path: ${{ inputs.versionNumber }}
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.credentials }}
          
      - name: Provision Azure Resources
        uses: azure/arm-deploy@v2
        with:
          failOnStdErr: false
          deploymentName: "${{ env.ARTIFACT_NAME }}${{inputs.environment}}"
          scope: subscription
          region: ${{ inputs.location }}
          subscriptionId: ${{ secrets.subscriptionId }}
          template: deploy/main.bicep
          parameters: >
            appName=${{ inputs.applicationName }}
            version=${{ inputs.versionNumber }}
            environment=${{ inputs.environment }}
            location=${{ inputs.location }}
            
      - name: "Deploy Azure Function App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cchat-fn-${{ inputs.applicationName }}-${{ inputs.environment }}'
          package: ${{ inputs.versionNumber }}            
            
#      - name: Zip function output
#        run: |
#          cd artifacts/${{ inputs.versionNumber }}
#          zip -r ../functionapp.zip .
#          cd .. 
#          
#      - name: Verify zip file exists
#        run: |
#          if [ ! -f "artifacts/functionapp.zip" ]; then
#          echo "Error: functionapp.zip does not exist"
#          exit 1
#          fi          
#            
#      - name: Deploy via Zip
#        run: |
#          az functionapp deployment source config-zip \
#          --resource-group cchat-rg-${{ inputs.applicationName }}-${{ inputs.environment }} \
#          --name cchat-fn-${{ inputs.applicationName }}-${{ inputs.environment }} \
#          --src artifacts/functionapp.zip \
#          --timeout 600
            
#      - name: Deploy Function App Package
#        uses: Azure/functions-action@v1
#        with:
#          app-name: "cchat-fn-${{ inputs.applicationName }}-${{ inputs.environment }}"
#          package: ${{ inputs.versionNumber }}            
            
#      - name: "Deploy Azure Function App"
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: "cchat-fn-${{ inputs.applicationName }}-${{ inputs.environment }}"
#          package: ${{ inputs.versionNumber }}
          
      
      - name: Logout from Azure
        uses: azure/cli@v2
        with:
          inlineScript:
            az logout                  
            
            