name: Restore and Build
on:
  workflow_call: 
    inputs: 
      project-path:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string
        default: '8.0.x'
        
jobs:
  restoreandbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            ${{inputs.dotnet-version}}
            
      - name: Restore .NET Tools
        run: dotnet tool restore
        
      - name: Check C# Code Formatting
        run: dotnet csharpier . --check
        
      - name: Restore Dependencies
        run: dotnet restore ${{inputs.project-path}}
        
      - name: Build Project
        run: dotnet build --configuration Release --no-restore ${{inputs.project-path}}
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" ${{inputs.project-path}}
        